#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Post-compile script for Paraglide debug wrapper
 * Watches for _index.js and wraps it with debug metadata
 */
export function wrapParaglideIndex(indexPath) {
  try {
    if (!fs.existsSync(indexPath)) {
      console.log('[paraglide-debug] _index.js not found at:', indexPath);
      return false;
    }

    const originalCode = fs.readFileSync(indexPath, 'utf-8');
    const originalPath = indexPath.replace('_index.js', '_original.js');

    // Extract function names
    const functionNames = [];
    const exportMatches = originalCode.matchAll(/export const (\w+) = /g);
    for (const match of exportMatches) {
      functionNames.push(match[1]);
    }

    if (functionNames.length === 0) {
      console.log('[paraglide-debug] No functions found in _index.js');
      return false;
    }

    console.log('[paraglide-debug] ✓ Found functions:', functionNames.join(', '));

    // Save original
    fs.writeFileSync(originalPath, originalCode, 'utf-8');

    // Create wrapper
    const wrapperCode = `// Debug wrapper for Paraglide messages
// Generated by vite-plugin-paraglide-debug
// Original code saved to _original.js

import * as _original from './_original.js';

// Debug wrapper function
function __debugWrap(text, key, params) {
  if (typeof text !== 'string') return text;
  const paramsStr = params && Object.keys(params).length > 0
    ? \` params:\${JSON.stringify(params)}\`
    : '';
  return \`<!-- paraglide:\${key}\${paramsStr} -->\${text}<!-- /paraglide:\${key} -->\`;
}

// Export wrapped versions of all message functions
${functionNames.map(name => `export const ${name} = (inputs, options) => {
  const result = _original.${name}(inputs, options);
  return __debugWrap(result, "${name}", inputs);
};`).join('\n')}
`;

    fs.writeFileSync(indexPath, wrapperCode, 'utf-8');

    console.log('[paraglide-debug] ✓ Wrapped _index.js (original saved to _original.js)');
    return true;
  } catch (err) {
    console.error('[paraglide-debug] Error wrapping _index.js:', err);
    return false;
  }
}

// If run directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const indexPath = process.argv[2] || './src/paraglide/messages/_index.js';
  wrapParaglideIndex(path.resolve(process.cwd(), indexPath));
}
