import { createDebugMiddleware } from './middleware.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Custom Vite plugin for ParaglideJS debug metadata injection
 * @param {Object} options - Plugin options
 * @param {string} options.outdir - Output directory where Paraglide generates files
 * @returns {import('vite').Plugin}
 */
export function paraglideBrowserDebugPlugin(options = {}) {
  const {
    outdir = './src/paraglide'
  } = options;

  let viteConfig;
  let isDebugMode = false;

  return {
    name: 'paraglide-browser-debug',
    enforce: 'post', // Run after the official Paraglide plugin

    configResolved(config) {
      viteConfig = config;
      // Check environment variable from Vite's loaded .env files
      isDebugMode = config.env.VITE_PARAGLIDE_BROWSER_DEBUG === 'true';
      console.log('[paraglide-debug] Plugin configured');
      console.log('[paraglide-debug] Debug mode:', isDebugMode);
      console.log('[paraglide-debug] Environment check:', config.env.VITE_PARAGLIDE_BROWSER_DEBUG);
    },

    // Resolve virtual module IDs
    resolveId(id) {
      if (id === '/@paraglide-debug/client.js') {
        return id; // Always mark as resolved
      }
      return null;
    },

    // Load virtual module content
    load(id) {
      // Serve virtual module
      if (id === '/@paraglide-debug/client.js') {
        // If debug mode is off, return empty script
        if (!isDebugMode) {
          return '// Paraglide debug mode is disabled';
        }

        const runtimePath = path.join(__dirname, '../runtime.js');

        try {
          const code = fs.readFileSync(runtimePath, 'utf-8');
          console.log('[paraglide-debug] ✓ Loaded client runtime');
          return code;
        } catch (err) {
          console.error('[paraglide-debug] Error loading client:', err);
          return 'console.error("Failed to load Paraglide debug client");';
        }
      }

      return null;
    },

    // Serve debug endpoints
    configureServer(server) {
      if (!isDebugMode) return;

      server.middlewares.use(createDebugMiddleware(viteConfig));

      console.log('[paraglide-debug] ✓ Serving translations at /@paraglide-debug/langs.json');
      console.log('[paraglide-debug] Note: For SvelteKit, add script tag to app.html conditioned on env variable');
    },

    // Transform _index.js to wrap with debug metadata
    transform(code, id) {
      const normalizedId = id.replace(/\\/g, '/');

      // Check if this is a request for the original (unwrapped) code
      const isOriginalQuery = normalizedId.includes('_index.js?original');
      const isIndexFile = normalizedId.includes('/paraglide/messages/') &&
                          normalizedId.includes('_index.js') &&
                          !isOriginalQuery;

      // Return stored original code when requested with ?original
      if (isOriginalQuery) {
        return {
          code: this.originalIndexCode,
          map: null
        };
      }

      if (!isDebugMode || !isIndexFile) {
        return null;
      }

      console.log('[paraglide-debug] ✓ Intercepting _index.js');

      // Store the original code
      this.originalIndexCode = code;
      this.originalIndexId = id;

      // Extract function names from exports
      const functionNames = [];
      const exportMatches = code.matchAll(/export const (\w+) = /g);
      for (const match of exportMatches) {
        functionNames.push(match[1]);
      }

      console.log('[paraglide-debug] Found message functions:', functionNames.join(', '));

      // Generate wrapper that imports original via ?original query
      const wrapperCode = `
// Debug wrapper for Paraglide messages
// Generated by vite-plugin-paraglide-debug

import * as _original from './_index.js?original';

// Debug wrapper function - stores text mapping in global registry
function __debugWrap(text, key, params) {
  if (typeof text !== 'string') return text;

  // Store mapping in global registry
  if (typeof window !== 'undefined') {
    window.__paraglideBrowserDebug = window.__paraglideBrowserDebug || {};
    window.__paraglideBrowserDebug.registry = window.__paraglideBrowserDebug.registry || new Map();
    window.__paraglideBrowserDebug.registry.set(text, {
      key: key,
      params: params || {},
      timestamp: Date.now()
    });
  }

  // Return plain text (no HTML manipulation)
  return text;
}

// Export wrapped versions of all message functions
${functionNames.map(name => `export const ${name} = (inputs, options) => {
  const result = _original.${name}(inputs, options);
  return __debugWrap(result, "${name}", inputs);
};`).join('\n')}
`;

      return {
        code: wrapperCode,
        map: null
      };
    },

    // Inject runtime script to build element registry (for standard Vite apps)
    transformIndexHtml: {
      order: 'pre',
      handler(html) {
        if (!isDebugMode) return html;

        // Inject script tag that loads from the served endpoint
        const scriptTag = '<script type="module" src="/@paraglide-debug/client.js"></script>';

        // Inject before closing </body> tag
        return html.replace('</body>', scriptTag + '\n</body>');
      }
    },

    // SvelteKit-specific hook for HTML transformation
    transformPageChunk({ html, done }) {
      if (!isDebugMode || !done) return null;

      // Inject script tag that loads from the served endpoint
      const scriptTag = '<script type="module" src="/@paraglide-debug/client.js"></script>';

      // Inject before closing </body> tag
      return html.replace('</body>', scriptTag + '\n</body>');
    }
  };
}
